docker:
  registry: registry.cynarski.pl
  namespace: LeDo
  name: ledo
  main_service: ledo
  shell: /bin/sh
modes:
  dev: container/container-compose.yml container/container-compose.dev.yml
  launch: container/container-compose.yml
