# .circleci/config.yml
version: 2.1
workflows:
  main:
    jobs:
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
jobs:
  release:
    docker:
      - image: cimg/go:1.20.6
    steps:
      - checkout
      - run:
          name: goreleaser 
          command: curl -sL https://git.io/goreleaser | bash
      - run:
          name: Trigger docker `paramah/dind` build
          command: |
            curl -X POST "https://drone.cynarski.pl/api/repos/Docker/dind/builds" -H "Authorization: Bearer ${DRONE_TOKEN}"